name: Pre-merge checks

on:
  workflow_call:
    secrets:
      DEV_F2F_PRE_MERGE_ROLE_ARN:
        required: true

jobs:
  setup:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    concurrency:
      group: build-pre-merge-${{ github.head_ref || github.ref_name }}
    outputs:
      sha_short: ${{ steps.vars.outputs.sha_short }}
    defaults:
      run:
        working-directory: ./deploy/
    steps:
      - name: Check out repository code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Get output variables
        id: vars
        run: |
          echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 22
          cache: 'npm'
          cache-dependency-path: 'src/package-lock.json'

      - name: Install dependencies
        run: cd ../src && npm ci

      - name: Setup SAM CLI
        uses: aws-actions/setup-sam@v2
        with:
          use-installer: true

      - name: SAM Build
        run: sam build -t template.yaml

      - name: Cache SAM build
        uses: actions/cache/save@v4
        with:
          path: deploy/.aws-sam
          key: sam-build-${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    needs: setup
    concurrency:
      group: deploy-pre-merge-${{ github.head_ref || github.ref_name }}
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Check out repository code
        uses: actions/checkout@v5

      - name: Assume temporary AWS role
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.DEV_F2F_PRE_MERGE_ROLE_ARN }}
          aws-region: eu-west-2

      - name: Steps for deployments
        run: |
          echo "Deployment steps will be added in separate tickets:"
          echo "Deploy API stack"
          echo "Deploy test harness stack"
          echo "Deploy IPV stub stack"

  test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    needs: deploy
    concurrency:
      group: test-pre-merge-${{ github.head_ref || github.ref_name }}
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Check out repository code
        uses: actions/checkout@v5
        with:
          submodules: true

      - name: Assume temporary AWS role
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.DEV_F2F_PRE_MERGE_ROLE_ARN }}
          aws-region: eu-west-2

      - name: Placeholder for tests
        run: |
          echo "Test execution will be added"

      - name: Placeholder for cleanup
        run: |
          echo "Stacks cleanup will be added"
