name: Pull Request CI
on:
  # Triggers the workflow on push or pull request events but only for the "main" or "develop" branch
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - ready_for_review
      - synchronize
    paths-ignore:
      - 'infra-l2-dynamo/**'
      - 'infra-l2-kms/**'
      - 'f2f-ipv-stub/**'
      - 'infra-l2-outbound-proxy/**'
      - 'yoti-stub/**'
      - 'gov-notify-stub/**'
      - 'test-harness/**'
      - 'post-office-stub/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Required for sam-validate step
permissions:
  id-token: write
  contents: read

env: # Only adding the variables in that are required for
  AWS_REGION: eu-west-2
  DEV_CRI_F2F_API_URL: ${{ secrets.DEV_CRI_F2F_API_URL }}
  DEV_IPV_F2F_STUB_URL: ${{ secrets.DEV_IPV_F2F_STUB_URL }}
  DEV_F2F_YOTI_STUB_URL: ${{ secrets.DEV_F2F_YOTI_STUB_URL }}
  DEV_F2F_EXPIRED_ACCESS_TOKEN: ${{ secrets.DEV_F2F_EXPIRED_ACCESS_TOKEN }}
  DEV_F2F_MISSING_SUB_ACCESS_TOKEN: ${{ secrets.DEV_F2F_MISSING_SUB_ACCESS_TOKEN }}
  DEV_F2F_TEST_HARNESS_URL: ${{ secrets.DEV_TEST_HARNESS_API_ENDPOINT }}
  DEV_F2F_GOV_NOTIFY_STUB_URL: ${{ secrets.DEV_F2F_GOV_NOTIFY_STUB_URL }}
  PACT_BROKER_USER: ${{ secrets.PACT_BROKER_USER }}
  PACT_BROKER_PASSWORD: ${{ secrets.PACT_BROKER_PASSWORD }}
  PACT_BROKER_URL: ${{ secrets.PACT_BROKER_URL }}?testSource=${{ secrets.PACT_BROKER_SOURCE_HEADER }}
  PACT_PROVIDER_NAME: ${{ secrets.PACT_PROVIDER_NAME }}
  PACT_PROVIDER_VERSION: ${{ secrets.PACT_PROVIDER_VERSION }}
  CLIENT_CONFIG: ${{ secrets.DEV_CLIENT_CONFIG }}

jobs:
  run-code-check:
    name: Code Checks
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./src/
    steps:
      - name: Check out repository code
        uses: actions/checkout@v5
        with:
          submodules: true

      - name: Setup nodeJS v22
        uses: actions/setup-node@v5
        with:
          node-version: 22

      - name: Set offline mirror path
        id: offline-mirror-path
        run: echo "mirror-dir=${GITHUB_WORKSPACE}/npm-packages-offline-cache" >> $GITHUB_OUTPUT

      - name: Cache npm offline-mirror
        uses: actions/cache@v4
        with:
          path: ${{ steps.offline-mirror-path.outputs.mirror-dir }}
          key: offline-mirror-oauth

      - name: Install dependencies
        run: npm ci

      - name: Run lint
        run: npm run lint

      - name: Archive lint results
        if: always()
        uses: actions/upload-artifact@v5
        with:
          name: lint-report
          path: src/reports/eslint/reportFile.html

      - name: Run Tests
        run: npm run test:unit

      - name: Run Infra checks
        run: npm run test:infra

      - name: Run Contract tests
        run: npm run test:contract:ci   
      
      - name: Kill DynamoDB 
        run: npm run kill:dynamodblocal

  sam-validate:
    name: SAM Validate
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./deploy/
    steps:
      - name: Check out repository code
        uses: actions/checkout@v5
        with:
          submodules: true

      - name: Setup SAM CLI
        uses: aws-actions/setup-sam@v2
        with:
          use-installer: true

      - name: Assume temporary AWS role
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.CRI_F2F_GH_VALIDATE_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Cache SAM builds
        uses: actions/cache@v4
        with:
          path: |
            ./di-ipv-cri-f2f-api/.aws-sam/cache
            ./di-ipv-cri-f2f-api/.aws-sam/deps
            ./di-ipv-cri-f2f-api/.aws-sam/build.toml
          key: sam-oauth

      - name: SAM Validate
        run: sam validate --region ${{ env.AWS_REGION }} -t template.yaml

      - name: CD and list
        run: |
          cd ../src
          pwd
          echo "ignore-scripts?"
          npm config get ignore-scripts

      - name: SAM Build
        run: sam build -t template.yaml

  # This is a temporary trigger for the pre-merge check, set up for testing purposes. A decision will be made later regarding the actual pre-merge trigger.
  # pre-merge-checks:
  #   uses: ./.github/workflows/pre-merge-check.yml
  #   secrets: inherit
