name: Unit tests

on:
  workflow_call:
    inputs:
      coverage-report:
        type: boolean
        required: false
        default: false
      coverage-artifact:
        type: string
        required: false
        default: "coverage"
    outputs:
      coverage-artifact:
        value: ${{ inputs.coverage-artifact }}

defaults:
  run:
    shell: bash
    working-directory: ./src/

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Pull repository
        uses: actions/checkout@v4

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Set offline mirror path
        id: offline-mirror-path
        run: echo "mirror-dir=${GITHUB_WORKSPACE}/npm-packages-offline-cache" >> $GITHUB_OUTPUT

      - name: Cache npm offline-mirror
        uses: actions/cache@v4
        with:
         path: ${{ steps.offline-mirror-path.outputs.mirror-dir }}
         key: offline-mirror-oauth

      - name: Install dependencies
        run: npm install

      - name: Run Unit tests
        run: npm run test:unit

      - name: Archive coverage results
        if: ${{ inputs.coverage-report }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.coverage-artifact }}
          retention-days: 3
          path: src/coverage/lcov.info
